
        <div class="row">
            <div class="col-md-12">

                <h1>Authoring</h1>

                <div class="panel panel-default">

                    <div class="panel-heading clearfix">
                        <a class="btn btn-default pull-left" href="<?php echo $this->url('item', ['action' => 'create']); ?>">Create new</a>
                    </div>

                    <table class="table">
                        <tbody>
                            <?php if ($this->authoringItems) : ?>
                            <?php echo $this->partialLoop('boxspaced/cms-workflow-module/workflow/authoring-item.phtml', $this->authoringItems) ?>
                            <?php else : ?>
                            <tr class="odd"><td width="100%">Empty result set</td><td colspan="3">&nbsp;</td></tr>
                            <?php endif; ?>
                        </tbody>
                    </table>

                </div>

                <?php echo $this->paginationControl(
                    $this->paginator,
                    'Sliding',
                    'boxspaced/cms-core-module/partial/pagination.phtml',
                    [
                        'route' => [
                            'name' => 'workflow',
                            'params' => [
                                'action' => 'authoring',
                            ],
                        ],
                    ]
                ); ?>

            </div>
        </div>
