
        <div class="row">
            <div class="col-md-12">

                <h1>Index of: Authoring</h1>

                <div class="actions">
                    <img src="/images/icons/add.png" alt="Add icon" />
                    <a class="link-button" href="<?php echo $this->url('item', ['action' => 'create']); ?>">Create new</a>
                </div>

                <table class="table">
                    <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th colspan="3">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($this->authoringItems) : ?>
                        <?php echo $this->partialLoop('boxspaced/cms-workflow-module/workflow/authoring-item.phtml', $this->authoringItems) ?>
                        <?php else : ?>
                        <tr class="odd"><td width="100%">Empty result set</td><td colspan="3">&nbsp;</td></tr>
                        <?php endif; ?>
                    </tbody>
                </table>

                <?php echo $this->paginationControl(
                    $this->paginator,
                    'Sliding',
                    'boxspaced/cms-workflow-module/workflow/admin-pagination.phtml',
                    [
                        'route' => [
                            'name' => 'workflow',
                            'params' => [
                                'action' => 'authoring',
                            ],
                        ],
                    ]
                ); ?>

            </div>
        </div>
