
                <fieldset>
                    <legend>Please confirm this action</legend>

                    <?php echo $this->messages() ?>

                    <?php
                    $form = $this->form;
                    $form->prepare();
                    ?>

                    <?php echo $this->form()->openTag($form) ?>

                        <?php echo $this->adminFormElement($form->get('id')) ?>
                        <?php echo $this->adminFormElement($form->get('moduleName')) ?>
                        <?php echo $this->adminFormElement($form->get('token')) ?>

                        <div class="form-group">
                            <div class="col-md-4 col-md-offset-4">

                                <?php
                                $form->get('confirm')->setAttribute('class', 'btn btn-danger');
                                echo $this->formElement($form->get('confirm'));
                                ?>

                            </div>
                        </div>

                    <?php echo $this->form()->closeTag() ?>

                </fieldset>
