
        <div class="row">
            <div class="col-md-12">

                <h1>Index of: Publishing</h1>

                <div id="send_back_dialog">
                    <div class="hd">Send back to author</div>
                    <div class="bd">
                        <form method="post" action="<?php echo $this->url('workflow', ['action' => 'send-back']); ?>">
                            <input type="hidden" name="moduleName" value="" />
                            <input type="hidden" name="id" value="" />
                            <label for="notes" style="display: block;">Add a note:</label>
                            <textarea name="notes" style="width: 28em; height: 8em;"></textarea>
                        </form>
                    </div>
                </div>

                <table class="table">
                    <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th colspan="5">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($this->publishingItems) : ?>
                        <?php echo $this->partialLoop('boxspaced/cms-workflow-module/workflow/publishing-item.phtml', $this->publishingItems) ?>
                        <?php else : ?>
                        <tr class="odd"><td width="100%">Empty result set</td><td colspan="5">&nbsp;</td></tr>
                        <?php endif; ?>
                    </tbody>
                </table>

                <?php echo $this->paginationControl(
                    $this->paginator,
                    'Sliding',
                    'boxspaced/cms-workflow-module/workflow/admin-pagination.phtml',
                    [
                        'route' => [
                            'name' => 'workflow',
                            'params' => [
                                'action' => 'publishing',
                            ],
                        ],
                    ]
                ); ?>

            </div>
        </div>
