<?php
use Boxspaced\CmsWorkflowModule\Service\WorkflowService;
?>
<tr class="<?php echo ($this->partialLoop()->getPartialCounter() % 2) ? 'odd' : 'even' ?>">

<td width="100%">
<div class="item-icon">
<img src="<?php echo $this->escapeHtmlAttr($this->typeIcon) ?>" alt="" title="<?php echo $this->escapeHtmlAttr($this->typeName) ?>" />
</div>
<div class="item-title"><em><?php echo $this->escapeHtml($this->name) ?></em></div>
<div class="item-detail">
Type: <em><?php echo $this->escapeHtml($this->typeName) ?></em><br />
Version: <em><?php echo $this->escapeHtml($this->workflowStatus) ?></em><br />
Authored by <em><?php echo $this->escapeHtml($this->authorUsername) ?></em> on <em><?php echo $this->date($this->authoredTime, 'l, F j, Y') ?></em> at <em><?php echo $this->date($this->authoredTime, 'H:i') ?></em></div></td>

<?php if ($this->moduleName !== 'block') : ?>
<?php if ($this->workflowStatus == WorkflowService::WORKFLOW_STATUS_NEW) : ?>
<td>
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Preview <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <?php foreach ($this->availableTemplates as $template) : ?>
            <li><a onclick="open_preview('<?php echo $this->url('content', ['slug' => $this->name], ['query' => ['preview' => 'publishing', 'templateId' => $template->id]]); ?>')">with <?php echo $this->escapeHtml($template->name) ?> template</a></li>
            <?php endforeach; ?>
        </ul>
    </div>
</td>
<?php else : ?>
<td><a class="btn btn-default" onclick="open_preview('<?php echo $this->url('content', ['slug' => $this->name], ['query' => ['preview' => 'publishing', 'contentId' => $this->id]]); ?>')">Preview</a></td>
<?php endif; ?>
<?php else : ?>
<td>&nbsp;</td>
<?php endif; ?>

<td>
    <img class="clickable-icon" src="/images/icons/notes.png" alt="Notes icon" title="Notes" data-toggle="modal" data-target="#notes-modal-<?php echo $this->moduleName ?>-<?php echo $this->id ?>" />
    <div class="modal" tabindex="-1" id="notes-modal-<?php echo $this->moduleName ?>-<?php echo $this->id ?>">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Notes</h4>
                </div>
                <div class="modal-body">
                    <p>
                        <?php if (empty($this->notes)) : ?>
                        No notes found
                        <?php else : ?>
                        <?php foreach ($this->notes as $note) : ?>
                        <?php echo $this->date($note->time, 'F j Y H:i') . ' - ' .
                        $this->escapeHtml($note->username) . ' - ' .
                        $this->escapeHtml($note->text) ?><br />
                        <?php endforeach; ?>
                        <?php endif; ?>
                    </p>
                </div>
            </div>
        </div>
    </div>
</td>

<td>
    <a id="<?php echo $this->escapeHtmlAttr($this->moduleName) ?>|<?php echo $this->escapeHtmlAttr($this->id) ?>" href="<?php echo $this->url('workflow', ['action' => 'send-back'], ['query' => ['moduleName' => $this->moduleName, 'id' => $this->id]]); ?>" class="workflow-send-back" title="Send back to author"><img src="/images/icons/arrow_left.png" alt="Arrow left icon" /></a>
</td>

<td>
    <a<?php if ($this->workflowStatus === WorkflowService::WORKFLOW_STATUS_UPDATE) : ?> class="link-button workflow-publish" title="Publish update"<?php else : ?> class="workflow-publish" title="Go to publishing options"<?php endif; ?> href="<?php echo $this->url($this->moduleName, ['action' => ($this->workflowStatus === WorkflowService::WORKFLOW_STATUS_UPDATE ? 'publish-update' : 'publish'), 'id' => $this->id]); ?>">
        <?php if ($this->workflowStatus === WorkflowService::WORKFLOW_STATUS_UPDATE) : ?>
            Publish
        <?php else : ?>
            <img src="/images/icons/publish.png" alt="Publish icon" />
        <?php endif ?>
    </a>
</td>

<td>
    <a href="<?php echo $this->url('workflow', ['action' => 'publishing-delete'], ['query' => ['moduleName' => $this->moduleName, 'id' => $this->id]]); ?>" class="workflow-delete" title="Delete"><img src="/images/icons/dustbin.png" alt="Delete icon" /></a>
</td>

</tr>
