<tr class="<?php echo ($this->partialLoop()->getPartialCounter() % 2) ? 'odd' : 'even' ?>">

<td width="100%">
<div class="item-icon">
<img src="<?php echo $this->escapeHtmlAttr($this->typeIcon) ?>" alt="" title="<?php echo $this->escapeHtmlAttr($this->typeName) ?>" />
</div>
<div class="item-title"><em><?php echo $this->escapeHtml($this->name) ?></em></div>
<div class="item-detail">
Type: <em><?php echo $this->escapeHtml($this->typeName) ?></em><br />
Version: <em><?php echo $this->escapeHtml($this->workflowStatus) ?></em><br />
Workflow stage: <em><?php echo $this->escapeHtml(ucfirst(strtolower($this->workflowStage))) ?></em><br />
Authored by <em>you</em> on <em><?php echo $this->date($this->authoredTime, 'l, F j, Y') ?></em> at <em><?php echo $this->date($this->authoredTime, 'H:i') ?></em></div></td>

<td><img class="notes-icon clickable-icon" src="/images/icons/notes.png" alt="Notes icon" title="Notes" /><div class="notes">
<div class="hd">Notes</div>
<div class="bd"><p>
    <?php if (empty($this->notes)) : ?>
    No notes found
    <?php else : ?>
    <?php foreach ($this->notes as $note) : ?>
    <?php echo $this->date($note->time, 'F j Y H:i') . ' - ' .
    $this->escapeHtml($note->username) . ' - ' .
    $this->escapeHtml($note->text) ?><br />
    <?php endforeach; ?>
    <?php endif; ?>
    </p></div>
</div></td>

<?php
$allowedStages = [
    Workflow\Model\WorkflowableInterface::WORKFLOW_STAGE_AUTHORING,
    Workflow\Model\WorkflowableInterface::WORKFLOW_STAGE_REJECTED,
];
?>

<?php if (in_array($this->workflowStage, $allowedStages)) : ?>
<td><a href="<?php echo $this->url($this->moduleName, ['action' => 'edit', 'id' => $this->id]); ?>" class="workflow-edit" title="Edit"><img src="/images/icons/edit.png" alt="Edit icon" /></a></td>
<?php else : ?>
<td><img src="/images/icons/none.png" /></td>
<?php endif; ?>

<?php if (in_array($this->workflowStage, $allowedStages)) : ?>
<td><a href="<?php echo $this->url('workflow', ['action' => 'authoring-delete'], ['query' => ['moduleName' => $this->moduleName, 'id' => $this->id]]); ?>" class="workflow-delete" title="Delete"><img src="/images/icons/dustbin.png" alt="Delete icon" /></a></td>
<?php else : ?>
<td><img src="/images/icons/none.png" /></td>
<?php endif; ?>

</tr>
